### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by rancidfrog** [bbqlinux/bbqiso#6]
```
mount: work/efiboot: mount failed: Unknown error -1
```

**Comment by codeworkx** [comment]
No problem here. Works like expected.

Writing to 'stdio:out/bbqlinux-2016.08.12-x86_64-mate.iso' completed
successfully.
[bbqmkiso] INFO: Done! | 2.3G out/bbqlinux-2016.08.12-x86_64-mate.iso


Mit freundlichen Grüßen

Daniel Hillenbrand
IT-Dienstleistungen

Am Sportplatz 10 | 97618 Hohenroth
Telefon: 09771 637 35 87 | Mobil: 0162 95 666 24
E-Mail: daniel.hillenbrand@codeworkx.de | Internet: www.codeworkx.de

2016-08-11 20:12 GMT+02:00 rancidfrog <notifications@github.com>:

**Comment by rancidfrog** [comment]
After recent full system upgrade, with all packages up-to-date,
I keep getting:
```
mkfs.fat 4.0 (2016-05-06)
mount: work/efiboot: mount failed: Unknown error -1
```

**Comment by rancidfrog** [comment]
When I build, (gnome, cinamon, and mate)
efiboot.img 41.9 MB (41,943,040 bytes)
But, in code
    truncate -s 40M ${work_dir}/iso/EFI/archiso/efiboot.img
Could this be it?
testing now with   **_truncate -s 42M_**

**Comment by rancidfrog** [comment]
https://github.com/bbqlinux/bbqiso/pull/7
